---
name: 'Setup Plone & Python'
description: 'Set up a specific version of Plone and Python, using pip, to test add-ons.'
author: 'Plone Foundation'
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    default: '3.8'
  plone-version:
    description: "Plone version to be used."
    default: '5.2'
  setuptools-version:
    description: "Setuptools version to be used."
    default: '65.5.0'
  additional-eggs:
    description: "Eggs/versions to be installed. i.e. `plone.restapi>=8.13.0`"
    default: ''
branding:
  icon: 'code'
  color: 'blue'
runs:
  using: "composite"
  steps:
    # python setup
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip" # caching pip dependencies

    # python install
    - name: Install updated versions of pip, setuptools and wheel
      shell: bash
      run: |
        pip install -U pip wheel "setuptools==${{ inputs.setuptools-version }}"

    # Plone install
    - name: Install Plone ${{ inputs.plone-version }} and plone.app.testing
      shell: bash
      run: |
        pip install Plone plone.app.testing -c https://dist.plone.org/release/${{ inputs.plone-version }}/constraints.txt

    # Additional eggs
    - name: Install additional eggs
      shell: bash
      if: ${{ inputs.additional-eggs }}
      run: |
        pip install "${{ inputs.additional-eggs }}"
