---
name: 'Setup Plone & Python'
description: 'Set up a specific version of Plone and Python, using pip, to test add-ons.'
author: 'Plone Foundation'
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    default: '3.8'
    required: true
  plone-version:
    description: "Plone version to be used."
    default: '5.2'
    required: true
  setuptools-version:
    description: "Setuptools version to be used. If not specified, we use the version from the constraints file of the chosen plone-version."
    default: ''
    required: false
  additional-packages:
    description: "Package versions to be installed. i.e. `plone.restapi>=8.13.0`"
    default: ''
    required: false
  additional-eggs:
    description: "Deprecated, use additional-packages instead."
    default: ''
    required: false
branding:
  icon: 'code'
  color: 'blue'
runs:
  using: "composite"
  steps:
    # python setup
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip" # caching pip dependencies

    # python install
    - name: Install updated versions of pip, setuptools and wheel
      shell: bash
      run: |
        pip install -U pip wheel setuptools -c https://dist.plone.org/release/${{ inputs.plone-version }}/constraints.txt

    # setuptools install
    - name: Install specific version of setuptools
      shell: bash
      if: ${{ inputs.setuptools-version }}
      run: |
        pip install -U "setuptools==${{ inputs.setuptools-version }}"

    # Plone install
    - name: Install Plone ${{ inputs.plone-version }} and plone.app.testing
      shell: bash
      run: |
        pip install Plone plone.app.testing -c https://dist.plone.org/release/${{ inputs.plone-version }}/constraints.txt

    # Additional packages
    - name: Install additional packages
      shell: bash
      if: ${{ inputs.additional-packages }}
      run: |
        pip install "${{ inputs.additional-packages }}"

    # Additional packages
    - name: "Deprecated: Install additional eggs"
      shell: bash
      if: ${{ inputs.additional-eggs }}
      run: |
        echo "additional-eggs is deprecated. Please rename to additional-packages, which does the same."
        pip install "${{ inputs.additional-eggs }}"
